//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardStatistic
    {
        public int Id { get; set; }
        public Nullable<int> TotalBooks { get; set; }
        public Nullable<int> TotalCategories { get; set; }
        public Nullable<int> TotalUsers { get; set; }
        public Nullable<int> ActiveBooks { get; set; }
        public Nullable<int> InactiveBooks { get; set; }
    }
}
